### ISSUE TITLE
How to show Host shared content screen

### ISSUE THREAD

**Issue by santoshgistto** [webex/webex-android-sdk-example#1]
How can we show only shared content screen by host and audio ?
We are planning to integrate webex to our existing tv app ( multiple tv's)
i don't see any sample in this example code
any help on this ?

**Comment by KunNiu** [comment]
@santoshgistto , you can mute/unmute local video by method `Call.setSendingVideo(boolean sending);` during a call, so if you don't want send video when sharing, of course you can use method `Call.setSendingVideo(false);` to close local video.
