### ISSUE TITLE
After authentication - email and password - am getting "We've encountered an error. Try again later.

### ISSUE THREAD

**Issue by SanthoshMKunthe** [webex/webex-android-sdk-example#11]
STEP 1 --> https://ibb.co/6JtkfGm -- selected "webex id". . .
STEP 2 --> https://ibb.co/d7c4Jk8 --  entered email. . .
STEP 3 --> https://ibb.co/FKqCfzT -- entered password. . .
STEP 4 --> https://ibb.co/P4jzyD7 -- THE ERROR. . .

i have got same error multiple times. . . am using https://ibb.co/jMx3sgp "webex/webex-android-sdk-example". . .

https://ibb.co/0jYZCSH
https://ibb.co/hBLJ2JJ
https://ibb.co/K0Jcj35
https://ibb.co/rdd5Cmh
https://ibb.co/sVYfLFQ
https://ibb.co/NW70fqc

**Comment by KunNiu** [comment]
@SanthoshMKunthe , this issue maybe caused by your account. Could you success login into any other Webex client through this account? 
You can try the Webex Teams clients, https://www.webex.com/downloads.html

**Comment by adamrangs** [comment]
@SanthoshMKunthe , the issue seems related to logging into IDP and not specific to SDK.  Please check if you account credentials are correct and if you are able to login via browser.  SDK only loads up the webview provided by the IDP.

**Comment by Mohindharan** [comment]
I have same issue account information is correct is it valid for free users?
