### ISSUE TITLE
Does not enter a video call with password.

### ISSUE THREAD

**Issue by boodahDEV** [webex/webex-android-sdk-example#18]
Hello, I' m trying to enter a Webex call with the meeting password, but the application remains in a loop, in which it does not validate the password that I passed through the "dial" function on the WebexAgent. By placing it in the "AlertDialog", it just doesn't validate it and relaunches the "AlertDialog".

Checking the execution in android studio, I get the following:
WebexError [errorCode = HOST_PIN_OR_MEETING_PASSWORD_REQUIRED, message = 423 / Locked / {"errorCode": 2423006, "message": "Meeting requires a moderator pin or guest pin to join".

Already validate that I am sending you the correct password.
Already validate that the "isModerator" is false for this case.

Any solution for this?

The truth, he enters and makes the connection to a video call that does not have the use of "MEETING PASSWORD". Simply by having a "pin" in the call, it no longer enters and breaks the application.

**Comment by jeffmars** [comment]
There was a bug in the 2.7 release that the KS demo defaults to. This was fixed in hotfix 2.7.0.2 and the lastest hotfix version is 2.7.0.6(https://github.com/webex/webex-android-sdk/tree/Hotfix/2.7.0.6). You can update the KS demo by doing the following and it should resolve the password issue. 

1) *Add *snapshot maven repo to project's build.gradle
```
maven {
            url 'https://devhub.cisco.com/artifactory/webexsdk-SNAPSHOT/'        
}
```

2) Change version number in app's build.gradle
```
implementation('com.ciscowebex:androidsdk:2.7.0.6-SNAPSHOT@aar', {
        transitive = true
        changing = true
    })
```

**Comment by boodahDEV** [comment]
Hello friend, thanks for your answer ...
I did the steps you indicated to add to my sdk demo as is, but it throws me the following error that I really do not understand to solve.

```console
   "errors": [{
     "status": 409,
     "message": "The repository 'webexsdk-SNAPSHOT' rejected the resolution of an artifact 'webexsdk-SNAPSHOT: com / webex / wme4android-release / 10.12.2.0 / wme4android-release-10.12.2.0.pom' due to conflict in the snapshot release handling policy. "
   }]
}
```
Similarly, this other:
```console
  Unable to resolve dependency for ': app @ debug / compileClasspath': Could not resolve com.webex: wme4android-release: 10.12.2.0.
  Disable offline mode and sync project
  Show Details
  Affected Modules: app
```

**Comment by boodahDEV** [comment]
Hello friend, thanks for your answer ...
Working!🔥🔥🔥🔥
