### ISSUE TITLE
Multistream support

### ISSUE THREAD

**Issue by diegofn** [webex/webex-android-sdk-example#5]
Hello everyone,

Can you help me, I tried to run this example, call to webex room but I don't see the auxiliary streams on the tabs?

I receive the following message on the log
2020-04-14 07:45:42.012 10272-10272/com.ciscowebex.androidsdk.kitchensink D/WmeSession:199: main  Remote SDP for video is multistream? false

Please, Can anyone help me guide how to enable it?

**Comment by olivierproffit** [comment]
Hi @diegofn unfortunately we have a current known issue with multistream support on Android SDK but the new Android SDK 2.5 supports new multiparty layout. Feel free to give a try and report back if it answer your needs

**Comment by diegofn** [comment]
Hello Olivier,

I download and tested the new sdk 2.5 and the multiparty and I don't see the multiparty participants.

Please, you can check the following log
https://gist.github.com/diegofn/28784bdc3e4952fefbd5e3409e07d28b#file-kitchenlog-L1605

And give me one some advice or clue about if we need to enable something to get independent participants streams.

**Comment by kliu** [comment]
Hi @diegofn, how many participants in the meeting? From the log, there are only two participants, d.nieto@calltechinc.com and d.nieto@calltechsa.com, the multiparty layout is only for three or more participants in the meeting.

**Comment by diegofn** [comment]
Hello @kliu 

We test with 4 participants and the result is the same. We don't get a multistream flow.
Remote SDP for video is multistream? false

https://gist.github.com/diegofn/853d4b77a8d370b05dd7d083d4a53402#file-kitchenlog-L1888

Thanks for your help

**Comment by olivierproffit** [comment]
@diegofn multistream is not working currently. It's a known issue we are working on.
But you can enjoy the 3 new multiparty views: https://github.com/webex/webex-android-sdk/wiki/Multiparty-video-view-layout-for-group-call

**Comment by olivierproffit** [comment]
Hi @diegofn 
If it's still important for your use case, could you use our feature request tool https://ciscocollaboration.aha.io/session/new and vote if existing already otherwise create a new one. 
Please make sure you document your expectations and your business case. This way, this feature request will go up in our priority list.
Closing this ticket as we track feature requests in Aha
