### ISSUE TITLE
Messages in the Message Fragment do not persist. All the messages will disappear when I click back button & get back to MessageFragment

### ISSUE THREAD

**Issue by NeerajaGandla** [webex/webex-android-sdk-example#8]
I'm trying to integrate this sdk into one of our apps. In the messaging option, I can send messages. If I login through webex teams website, I can view the messages I sent. The messages will be received/sent when I'm in the MessageFragment. But if I click back button, the list becomes empty. I don't them those again. How can I persist all the messages received/sent during the session?

**Comment by NeerajaGandla** [comment]
I put the below code as per the sdk. But it's never triggered even when people send me messages.

```
 messageClient.setMessageObserver(evt -> {
            if (evt instanceof MessageObserver.MessageReceived) {
                MessageObserver.MessageReceived event = (MessageObserver.MessageReceived) evt;
                Ln.i("message: " + event.getMessage());
                adapterMessage.mData.add(event.getMessage());
                adapterMessage.notifyDataSetChanged();
                //if (event.getMessage().getPersonEmail().equals("sparksdktestuser16@tropo.com")) {
                textStatus.setText("");
                //}
            } else if (evt instanceof MessageObserver.MessageDeleted){
                MessageObserver.MessageDeleted event = (MessageObserver.MessageDeleted) evt;
                Ln.i("message deleted " + event.getMessageId());
            }
        });```

**Comment by KunNiu** [comment]
@NeerajaGandla , Kitchensink is only a demo app show how to use SDK, developer could storage messages in their own app.

**Comment by adamrangs** [comment]
@NeerajaGandla , Kitchen Sink is a representative of how the SDK APIs can be used.  The requested feature needs to be implemented by developers in their app with their own enhancements.
