### ISSUE TITLE
Connection is established only as a matter of chance.

### ISSUE THREAD

**Issue by NeerajaGandla** [webex/webex-android-sdk-example#9]
I have integrated the SDK in one of our apps. When users join a space, they're not connected. The connection is seldom established. Despite having network connection, the connection is not established. Even if it's connected, the audio/video is seldom sent. I have used the code exactly as in the example SDK.

**Comment by olivierproffit** [comment]
@NeerajaGandla the android example works for me. You can try directly the apk from here: https://github.com/webex/webex-android-sdk-example/releases/tag/2.5.0
If it doesn't work for you, our great developer support can help you troubleshoot: https://developer.webex.com/support

**Comment by NeerajaGandla** [comment]
@olivierproffit 
I installed the app on 2 devices from the release you mentioned. I logged in using different guest tokens in each device. They are both added as participants of a space. So I clicked on that space & click dial button. I see blank screen in both the devices. Or I see "dial Failed" error message.
![WhatsApp Image 2020-08-10 at 11 37 34 AM (1)](https://user-images.githubusercontent.com/26622768/89755699-f62dd000-dafd-11ea-9e3d-048ecbd556d6.jpeg)
![WhatsApp Image 2020-08-10 at 11 37 34 AM](https://user-images.githubusercontent.com/26622768/89755710-fb8b1a80-dafd-11ea-89e6-533aa21c3ac9.jpeg)

**Comment by olivierproffit** [comment]
@NeerajaGandla please reach out to our great developer support: https://developer.webex.com/support

**Comment by NeerajaGandla** [comment]
Sure. I noticed that if I use the Example app with webex registered accounts, it works a bit better. But if I use the JWT to login, I'm facing issues. As soon as a second user joins, he will be disconnected and exited from the space.
